services:
  db_test:
    image: postgres
    container_name: trello-lite-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trello_lite_test
    ports:
      - '5433:5432'
    volumes:
      - trello-lite-test-data:/var/lib/postgresql/data

volumes:
  trello-lite-test-data:
