services:
  db:
    image: postgres
    container_name: trello-lite-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trello_lite
    ports:
      - '5432:5432'
    volumes:
      - trello-lite-data:/var/lib/postgresql/data

volumes:
  trello-lite-data:
